#!/usr/bin/env python3
import json
import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
DATASET = ROOT / "專題預設數據 (1)"
BOOKS_PATH = DATASET / "書籍資料" / "Books.json"
USERS_PATH = DATASET / "使用者資料" / "Users.json"
BORROW_RECORDS_PATH = DATASET / "借還紀錄資料" / "Borrow_records.json"
OUTPUT_PATH = ROOT / "sql" / "seed.sql"

PASSWORD_123_HASH = "ef92b778bafe771e89245b89ecbc08a44a4e166c06659911881f383d4473e94f"
ADMIN_123_HASH = "240be518fabd2724ddb6f04eeb1da5967448d7e831c08c8fa822809f74c720a9"


def sql_string(value):
    if value is None:
        return "NULL"
    return "'" + str(value).replace("\\", "\\\\").replace("'", "''") + "'"


def sql_int(value):
    if value is None:
        return "NULL"
    return str(int(value))


def relative_date_expr(value):
    if value is None:
        return "NULL"
    match = re.fullmatch(r"(-?\d+)\s+days", value.strip())
    if not match:
        raise ValueError(f"Unsupported relative date value: {value}")
    return f"DATE_ADD(NOW(), INTERVAL {int(match.group(1))} DAY)"


def join_list(values):
    return ", ".join(values or [])


def values_line(values):
    return "(" + ", ".join(values) + ")"


def main():
    books = json.loads(BOOKS_PATH.read_text(encoding="utf-8"))
    users = json.loads(USERS_PATH.read_text(encoding="utf-8"))
    borrow_records = json.loads(BORROW_RECORDS_PATH.read_text(encoding="utf-8"))

    lines = [
        "-- Generated by scripts/generate_seed.py from 專題預設數據 (1).",
        "-- Import sql/schema.sql first, then this file.",
        "USE library_system;",
        "SET NAMES utf8mb4;",
        "SET FOREIGN_KEY_CHECKS = 0;",
        "TRUNCATE TABLE borrow_records;",
        "TRUNCATE TABLE book_isbns;",
        "TRUNCATE TABLE books;",
        "TRUNCATE TABLE users;",
        "SET FOREIGN_KEY_CHECKS = 1;",
        "START TRANSACTION;",
        "",
        "-- 20 users from Users.json. Password values are preserved as provided.",
        "INSERT INTO users (student_no, name, password_hash, role_level, created_at, status) VALUES",
    ]

    user_rows = [
        values_line([
            sql_string(user["student_no"]),
            sql_string(user["name"]),
            sql_string(user["password"]),
            sql_string(user["role_level"]),
            sql_string(user["created_at"]),
            sql_string(user["status"]),
        ])
        for user in users
    ]
    user_rows.extend([
        values_line([
            sql_string("S001"),
            sql_string("Demo Normal Student"),
            sql_string(PASSWORD_123_HASH),
            sql_string("NORMAL"),
            "NOW()",
            sql_string("ACTIVE"),
        ]),
        values_line([
            sql_string("S002"),
            sql_string("Demo VIP Student"),
            sql_string(PASSWORD_123_HASH),
            sql_string("VIP"),
            "NOW()",
            sql_string("ACTIVE"),
        ]),
        values_line([
            sql_string("admin"),
            sql_string("System Administrator"),
            sql_string(ADMIN_123_HASH),
            sql_string("ADMIN"),
            "NOW()",
            sql_string("ACTIVE"),
        ]),
    ])
    lines.append(",\n".join(user_rows) + ";")
    lines.append("")

    lines.extend([
        "-- 200 books from Books.json. Auto-increment IDs are preserved by insertion order.",
        "INSERT INTO books (title, authors, subjects, publisher, publish_year, edition, format_desc, source, note, status) VALUES",
    ])
    book_rows = [
        values_line([
            sql_string(book.get("題名")),
            sql_string(join_list(book.get("作者"))),
            sql_string(join_list(book.get("主題"))),
            sql_string(book.get("出版者")),
            sql_int(book.get("出版年")),
            sql_string(book.get("版本")),
            sql_string(book.get("格式")),
            sql_string(book.get("資料來源")),
            sql_string(book.get("附註")),
            sql_string("AVAILABLE"),
        ])
        for book in books
    ]
    lines.append(",\n".join(book_rows) + ";")
    lines.append("")

    isbn_rows = []
    for index, book in enumerate(books, start=1):
        for isbn in book.get("識別號") or []:
            isbn_rows.append(values_line([str(index), sql_string(isbn)]))
    if isbn_rows:
        lines.extend([
            "-- ISBNs split into a child table.",
            "INSERT INTO book_isbns (book_id, isbn) VALUES",
            ",\n".join(isbn_rows) + ";",
            "",
        ])

    lines.extend([
        "-- 30 JSON borrow records plus demo-account history.",
        "INSERT INTO borrow_records (user_id, book_id, borrow_date, due_date, return_date, borrow_days, created_at) VALUES",
    ])
    record_rows = [
        values_line([
            str(record["user_id"]),
            str(record["book_id"]),
            relative_date_expr(record["borrow_date"]),
            relative_date_expr(record["due_date"]),
            relative_date_expr(record["return_date"]),
            sql_int(record["borrow_days"]),
            relative_date_expr(record["created_at"]),
        ])
        for record in borrow_records
    ]
    record_rows.extend([
        values_line([
            "21",
            "196",
            "DATE_ADD(NOW(), INTERVAL -2 DAY)",
            "DATE_ADD(NOW(), INTERVAL 5 DAY)",
            "NULL",
            "7",
            "DATE_ADD(NOW(), INTERVAL -2 DAY)",
        ]),
        values_line([
            "21",
            "197",
            "DATE_ADD(NOW(), INTERVAL -12 DAY)",
            "DATE_ADD(NOW(), INTERVAL -5 DAY)",
            "DATE_ADD(NOW(), INTERVAL -4 DAY)",
            "7",
            "DATE_ADD(NOW(), INTERVAL -12 DAY)",
        ]),
        values_line([
            "22",
            "198",
            "DATE_ADD(NOW(), INTERVAL -10 DAY)",
            "DATE_ADD(NOW(), INTERVAL 4 DAY)",
            "NULL",
            "14",
            "DATE_ADD(NOW(), INTERVAL -10 DAY)",
        ]),
    ])
    lines.append(",\n".join(record_rows) + ";")
    lines.append("")
    lines.extend([
        "-- Reflect active borrow records in book status and reserve two unused books for admin testing.",
        "UPDATE books SET status = 'AVAILABLE';",
        "UPDATE books",
        "SET status = 'BORROWED'",
        "WHERE book_id IN (SELECT DISTINCT book_id FROM borrow_records WHERE return_date IS NULL);",
        "UPDATE books",
        "SET status = 'REMOVED'",
        "WHERE book_id IN (199, 200)",
        "  AND book_id NOT IN (SELECT DISTINCT book_id FROM borrow_records WHERE return_date IS NULL);",
        "",
        "COMMIT;",
        "",
    ])

    OUTPUT_PATH.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {OUTPUT_PATH.relative_to(ROOT)} with {len(users)} JSON users, {len(books)} JSON books, and {len(borrow_records)} JSON borrow records.")


if __name__ == "__main__":
    main()
